[package]
name = "hyperion"
version = "0.1.0"
edition = "2024"

[dependencies]
warp = { version = "0.4.2", features = ["server"] }
tokio = { version = "1.48.0", features = ["full"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres"] }
futures = "0.3"
